# Generated by Django 4.0 on 2022-01-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.TextField()),
                ('serivce_desc', models.TextField()),
                ('service_price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'Service',
            },
        ),
    ]
