# Generated by Django 4.0 on 2022-01-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_service_desc', models.TextField()),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garage.service')),
            ],
            options={
                'db_table': 'SubService',
            },
        ),
    ]
