# Generated by Django 4.0 on 2022-01-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_subservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('bill_amount', models.FloatField()),
            ],
            options={
                'db_table': 'Billing',
            },
        ),
    ]
