# Generated by Django 3.2.5 on 2022-01-23 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_date', models.DateTimeField(auto_now_add=True)),
                ('bill_amount', models.FloatField()),
            ],
            options={
                'db_table': 'billing',
            },
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
                ('serivce_desc', models.TextField()),
                ('service_price', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('ph_no', models.IntegerField(max_length=10)),
                ('address', models.TextField()),
                ('area', models.TextField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_plate', models.TextField(max_length=10, unique=True)),
                ('km', models.IntegerField(blank=True, null=True)),
                ('due_km', models.IntegerField(blank=True, null=True)),
                ('brand', models.TextField()),
                ('model_name', models.TextField()),
                ('chassis_no', models.TextField(unique=True)),
                ('engine_no', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'vehicle',
            },
        ),
        migrations.CreateModel(
            name='mapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('billId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageApp.billing')),
                ('serviceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageApp.service')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageApp.user')),
                ('vechileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garageApp.vehicle')),
            ],
            options={
                'db_table': 'mapper',
            },
        ),
    ]
