# Generated by Django 3.2.5 on 2022-01-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garageApp', '0003_auto_20220123_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bill',
            new_name='billing',
        ),
        migrations.AlterModelTable(
            name='billing',
            table='billing',
        ),
    ]
